version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
    environment:
      DB_CONNECTION: sqlite
      APP_ENV: local
      APP_KEY: base64:gYah9bJBC66UGM3Txn3M1NOtrUAjpo+865rzYlXZYsQ=
      # Add other environment variables as needed

  # Optional: Add a database service if needed
  # db:
  #   image: mysql:5.7
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: laravel
  #   ports:
  #     - "3306:3306"
